version: '3.9'
services:
  backend:
    build: server/
    ports:
      - 8000:3000
    volumes:
      - ./server/:/app
    depends_on:
      - db
    environment:
      DATABASE_TYPE: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: admin

  frontend:
    build: client/
    ports:
      - 3000:3000
    volumes:
      - ./client/:/app
    depends_on:
      - db
      - backend

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33066:3306
    volumes:
      - .dbdata:/var/lib/mysql
